
<div class="container">
  <div class="row p-3 justify-content-center">
    <form action="inserir_pedido" method="post">
      <div class="col-12 p-3 text-center">
        <label for="">Inserir novo pedido</label>
        <input name="numero_pedido" type="number" class="form-control text-center shadow" placeholder="Novo pedido...">
      </div>
      <div class="col-12 text-center m-auto">
        <button type="submit" class="btn btn-lg btn-primary rounded shadow">Inserir</button>
      </div>
    </form>
  </div>
</div>

<div class="container-fluid mt-2">
  <div class="row m-3">
    <div class="col shadow m-2 p-3 bg-light">
      <div class="p-3 mt-2 rounded">
        <h1 class="text-center text-warning">Em Separação<i class="bi bi-cart-plus"></i></h1>
      </div>

      <div id="pedidosSeparacao" class="row justify-content-center p-3">
      <?php foreach ($this->view->listarPedidoSeparacao as $key => $value) { ?>
            <div class="card bg-white shadow rounded-custom border-0 m-2" style="width: 18rem;">
                <div class="card-body">
                <h5 class="text-warning float-start"><?php echo $value['numero_pedido'] ?></h5>
                <button class=" btn btn-sm float-end" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-three-dots-vertical"></i></button>
                <ul class="dropdown-menu shadow" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item text-success" href="/mudar_status?numero_pedido=<?php echo $value['id'] ?>&status=2">Separado <i class="bi bi-check float-end"></i></a></li>
                    <li><a class="dropdown-item text-danger" href="#" data-bs-toggle="modal" data-bs-target="#excluir-pedido<?php echo $value['id'] ?>">Excluir <i class="bi bi-x float-end"></i></a></li>
                </ul>
                </div>
            </div>
            <!-- Modal excluir pedido -->
            <div class="modal fade" id="excluir-pedido<?php echo $value['id'] ?>" data-bs-backdrop="static" data-bs-backdrop="false" data-bs-keyboard="false" tabindex="-1" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content bg-transparent border-0">
                        <div class="container-fluid bg-dark text-white shadow">
                            <div class="modal-body p-1">
                                <div class="row p-1">
                                    <div class="col-12 col-sm-12 p-3 m-auto">
                                        <div class="row p-3 m-auto">
                                            <div class=" col p-3 small mb-3">
                                                <h5 class="text-center">Atenção <i class="bi bi-exclamation-triangle"></i></h5>
                                                <div class="row g-3 mt-2">
                                                    <div class="col-12 text-center">
                                                        <h6>Deseja realmente excluir o pedodo?</h6>
                                                        <h6><?php echo $value['numero_pedido'] ?></h6>
                                                    </div>
                                                </div>
                                            </div>
                                            <hr>
                                            <div class="col">
                                                <div class="col float-end">
                                                    <button type="button" class="btn btn-sm text-white" data-bs-dismiss="modal">Cancelar <i class="bi bi-x"></i></button>
                                                    <a href="/excluir?numero_pedido=<?php echo $value['id'] ?>" class="btn btn-sm text-white" data-toggle="tooltip" data-placement="top" title="Excluir">Sim <i class="bi bi-check"></i></a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <?php } ?>
        </div>
    </div>

    <div class="col shadow m-2 p-3 bg-light">
      <div class="p-3 mt-2 rounded">
        <h1 class="text-center text-success">Aguardando Retirada <i class="bi bi-cart-check"></i></h1>
      </div>

      <div id="pedidosRetirada" class="row justify-content-center p-3">
      <?php foreach ($this->view->dados as $key => $value) { ?>
            <div class="card bg-white shadow rounded-custom border-0 m-2" style="width: 18rem;">
                <div class="card-body">
                <h5 class="text-success float-start"><?php echo $value['numero_pedido'] ?></h5>
                <button class="btn btn-sm float-end" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-three-dots-vertical"></i></button>
                <ul class="dropdown-menu shadow" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item text-success" href="#" data-bs-toggle="modal" data-bs-target="#pedido-separado">Concluído <i class="bi bi-check float-end"></i></a></li>
                    <li><a class="dropdown-item text-danger" href="#" data-bs-toggle="modal" data-bs-target="#excluir-retirada<?php echo $value['id'] ?>">Excluir <i class="bi bi-x float-end"></i></a></li>
                </ul>
                </div>
            </div>
              <!-- Modal excluir pedido -->
              <div class="modal fade" id="excluir-retirada<?php echo $value['id'] ?>" data-bs-backdrop="static" data-bs-backdrop="false" data-bs-keyboard="false" tabindex="-1" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content bg-transparent border-0">
                        <div class="container-fluid bg-dark text-white shadow">
                            <div class="modal-body p-1">
                                <div class="row p-1">
                                    <div class="col-12 col-sm-12 p-3 m-auto">
                                        <div class="row p-3 m-auto">
                                            <div class=" col p-3 small mb-3">
                                                <h5 class="text-center">Atenção <i class="bi bi-exclamation-triangle"></i></h5>
                                                <div class="row g-3 mt-2">
                                                    <div class="col-12 text-center">
                                                        <h6>Deseja realmente excluir o pedodo?</h6>
                                                        <h6><?php echo $value['numero_pedido'] ?></h6>
                                                    </div>
                                                </div>
                                            </div>
                                            <hr>
                                            <div class="col">
                                                <div class="col float-end">
                                                    <button type="button" class="btn btn-sm text-white" data-bs-dismiss="modal">Cancelar <i class="bi bi-x"></i></button>
                                                    <a href="/excluir?numero_pedido=<?php echo $value['id'] ?>" class="btn btn-sm text-white" data-toggle="tooltip" data-placement="top" title="Excluir">Sim <i class="bi bi-check"></i></a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
              </div>
            <?php } ?>
        </div>
    </div>
  </div>
</div>
