<script src="/js/jquery-3.6.0.min.js"></script>
<div class="container">
    <div class="row p-3 mt-2">
        
        <div class="col-6 p-3 text-center m-auto">
            <h4 for="">Inserir novo pedido</h4>
            <form id="novo-pedido" action="inserir_pedido" method="post">
                <div class="input-group mb-3">
                    <input type="text" class="form-control shadow" data-name="form-novo-pedido" name="numero_pedido" placeholder="Novo pedido..." required>
                    <div class="input-group-append">
                        <button id="button-novo-pedido" type="submit" class="btn btn-success rounded shadow">Inserir <i class="bi bi-cart3"></i></button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-6 text-center m-auto">
            <button type="button" class="btn btn-outline-success rounded shadow">Ver pedidos Finalizados e cancelados <i class="bi bi-cart-check"></i></button>
        </div>
    </div>
</div>

<div id="container" class="container-fluid mt-2">
    <div class="row">
        <div class="col m-2 p-3">
            <div class="p-3 mt-2">
                <h3 class="text-center text-warning">Em Separação<i class="bi bi-cart-plus"></i></h3>
            </div>
            <div id="pedidosSeparacao" class="row justify-content-center p-2">
            <?php foreach ($this->view->listarPedidoSeparacao as $key => $value) { ?>
                <div class="card bg-white shadow rounded-custom border-0 m-2" style="width: 15rem;">
                    <div class="card-body">
                    <h5 class="text-warning float-start"><?php echo $value['numero_pedido'] ?></h5>
                    <button class=" btn btn-sm float-end" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-three-dots-vertical"></i></button>
                    <ul class="dropdown-menu shadow" aria-labelledby="navbarDropdown">
                        <li>
                            <!-- <form id="ped-separado<?php echo $value['id'] ?>" action="/mudar_status" method="get">
                                <input type="hidden" name="id_pedido" value="<?php echo $value['id'] ?>">
                                <input type="hidden" name="status" value="2">
                            <button class="dropdown-item" type="submit">Separado <i class="bi bi-cart-check float-end text-success"></i></button>
                            </form> -->
                            <a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#marcar-pedido-separado<?php echo $value['id'] ?>">Separado <i class="bi bi-cart-check float-end text-success"></i></a>
                            <!-- <a class="dropdown-item" href="/mudar_status?id_pedido=<?php echo $value['id'] ?>&status=2">Separado <i class="bi bi-cart-check float-end text-success"></i></a> -->
                        </li>
                        <li>
                            <a class="dropdown-item" href="/mudar_status?id_pedido=<?php echo $value['id'] ?>&status=4">Cancelar <i class="bi bi-cart-x float-end"></i></a></li>
                        <li>
                            <a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#excluir-pedido<?php echo $value['id'] ?>">Excluir <i class="bi bi-trash float-end text-danger"></i></a>
                        </li>
                    </ul>
                    </div>
                </div>
                
                <!-- Modal excluir pedido -->
                <div class="modal fade" id="excluir-pedido<?php echo $value['id'] ?>" data-bs-backdrop="static" data-bs-backdrop="false" data-bs-keyboard="false" tabindex="-1" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered">
                        <div class="modal-content bg-transparent border-0">
                            <div class="container-fluid bg-dark text-white shadow">
                                <div class="modal-body p-1">
                                    <div class="row p-1">
                                        <div class="col-12 col-sm-12 p-3 m-auto">
                                            <div class="row p-3 m-auto">
                                                <div class=" col p-3 small mb-3">
                                                    <h5 class="text-center">Atenção <i class="bi bi-exclamation-triangle"></i></h5>
                                                    <div class="row g-3 mt-2">
                                                        <div class="col-12 text-center">
                                                            <h6>Deseja realmente excluir o pedodo?</h6>
                                                            <h6><?php echo $value['numero_pedido'] ?></h6>
                                                        </div>
                                                    </div>
                                                </div>
                                                <hr>
                                                <div class="col">
                                                    <div class="col float-end">
                                                        <button type="button" class="btn btn-sm text-white" data-bs-dismiss="modal">Cancelar <i class="bi bi-x"></i></button>
                                                        <a href="/excluir?numero_pedido=<?php echo $value['id'] ?>" class="btn btn-sm text-white" data-toggle="tooltip" data-placement="top" title="Excluir">Sim <i class="bi bi-check"></i></a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <?php } ?>
            </div>
        </div>

        <div class="col m-2 p-3">
            <div class="p-3 mt-2">
                <h3 class="text-center text-success">Aguardando Retirada <i class="bi bi-cart-check"></i></h3>
            </div>
            <div id="pedidosRetirada" class="row justify-content-center p-3">
            <?php foreach ($this->view->dados as $key => $value) { ?>
                <div class="card bg-white shadow rounded-custom border-0 m-2" style="width: 15rem;">
                    <div class="card-body">
                    <h5 class="text-success float-start"><?php echo $value['numero_pedido'] ?></h5>
                    <button class="btn btn-sm float-end" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-three-dots-vertical"></i></button>
                    <ul class="dropdown-menu shadow" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#retirar-pedido<?php echo $value['id'] ?>">Concluír | Retirar <i class="bi bi-check float-end text-success"></i></a></li>
                        <li><a class="dropdown-item" href="/mudar_status?id_pedido=<?php echo $value['id'] ?>&status=4">Cancelar <i class="bi bi-cart-x float-end"></i></a></li>
                        <li><a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#excluir-retirada<?php echo $value['id'] ?>">Excluir <i class="bi bi-trash float-end text-danger"></i></a></li>
                    </ul>
                    </div>
                </div>
                <!-- Modal excluir pedido-retirada -->
                <div class="modal fade" id="excluir-retirada<?php echo $value['id'] ?>" data-bs-backdrop="static" data-bs-backdrop="false" data-bs-keyboard="false" tabindex="-1" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered">
                        <div class="modal-content bg-transparent border-0">
                            <div class="container-fluid bg-dark text-white shadow">
                                <div class="modal-body p-1">
                                    <div class="row p-1">
                                        <div class="col-12 col-sm-12 p-3 m-auto">
                                            <div class="row p-3 m-auto">
                                                <div class=" col p-3 small mb-3">
                                                    <h5 class="text-center">Atenção <i class="bi bi-exclamation-triangle"></i></h5>
                                                    <div class="row g-3 mt-2">
                                                        <div class="col-12 text-center">
                                                            <h6>Deseja realmente excluir o pedodo?</h6>
                                                            <h6><?php echo $value['numero_pedido'] ?></h6>
                                                        </div>
                                                    </div>
                                                </div>
                                                <hr>
                                                <div class="col">
                                                    <div class="col float-end">
                                                        <button type="button" class="btn btn-sm text-white" data-bs-dismiss="modal">Cancelar <i class="bi bi-x"></i></button>
                                                        <a href="/excluir?numero_pedido=<?php echo $value['id'] ?>" class="btn btn-sm text-white" data-toggle="tooltip" data-placement="top" title="Excluir">Sim <i class="bi bi-check"></i></a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Modal Retirar Pedido -->
                <div class="modal fade" id="retirar-pedido<?php echo $value['id'] ?>" data-bs-backdrop="static" data-bs-backdrop="false" data-bs-keyboard="false" tabindex="-1" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered">
                        <div class="modal-content bg-transparent border-0">
                            <div class="container-fluid bg-white shadow">
                                <div class="modal-body p-1">
                                    <div class="row p-1">
                                        <div class="col-12 col-sm-12 p-3 m-auto">
                                            <div class="row p-3 m-auto">
                                                <div class=" col p-3 small mb-3">
                                                    <h5 class="text-center text-success">Retirada de Pedido <i class="bi bi-check"></i></h5>
                                                    <div class="row g-3 mt-2">
                                                        <div class="col-12 text-center">
                                                            <h6>Pedido: <?php echo $value['numero_pedido'] ?></h6>
                                                        </div>
                                                    </div>
                                                </div>
                                                <form action="retirar_pedido" method="post">
                                                    <div class="form-group">
                                                        <label>Nome do Responsável </label>
                                                        <input type="text" class="form-control" name="nome_responsavel">
                                                        <input type="hidden" class="form-control" name="id_pedido" value="<?php echo $value['id'] ?>">
                                                        <input type="hidden" class="form-control" name="status" value="3">
                                                        <input type="hidden" class="form-control" name="user" value="Pedro Silva">
                                                        </div>
                                                        <div class="form-group mt-1">
                                                        <label>Telefone</label>
                                                        <input type="text" class="form-control" name="telefone" placeholder="(21) 99999-9999">
                                                    </div>

                                                    <div class="form-group mt-1">
                                                        <label>Placa do Veículo</label>
                                                        <input type="text" class="form-control" name="placa_veiculo" placeholder="RIO1234">
                                                    </div>
                                                    <div class="form-group mt-1">
                                                        <label>Tipo Veículo</label>
                                                        <input type="text" class="form-control" name="tipo_veiculo" placeholder="Moto, Carro ou Outros">
                                                    </div>
                                                    <hr>
                                                    <div class="col">
                                                        <div class="col float-end">
                                                            <button type="button" class="btn" data-bs-dismiss="modal">Cancelar <i class="bi bi-x"></i></button>
                                                            <button type="submit" class="btn">Confirmar <i class="bi bi-check"></i></button>
                                                        </div>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            <?php } ?>
            </div>
        </div>
    </div>
</div>


<?php foreach ($this->view->listarPedidoSeparacao as $key => $value) { ?>
    <div id="modal">
    <!-- Modal marcar-pedido-separado -->
    <div class="modal fade" id="marcar-pedido-separado<?php echo $value['id'] ?>" data-bs-backdrop="static" data-bs-backdrop="false" data-bs-keyboard="false" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content bg-transparent border-0">
                <div class="container-fluid bg-warning text-white shadow">
                    <div class="modal-body p-1">
                        <div class="row p-1">
                            <div class="col-12 col-sm-12 p-3 m-auto">
                                <div class="row p-3 m-auto">
                                    <div class=" col p-3 small mb-3">
                                        <h5 class="text-center">Atenção <i class="bi bi-exclamation-triangle"></i></h5>
                                        <div class="row g-3 mt-2">
                                            <div class="col-12 text-center">
                                                <h6>Deseja mover pedido para Aguardando Retirada?</h6>
                                                <h6>Pedido: <?php echo $value['numero_pedido'] ?></h6>
                                            </div>
                                        </div>
                                    </div>
                                    <hr>
                                    <div class="col">
                                    <form id="ped-separado<?php echo $value['id'] ?>" action="/mudar_status" method="post">
                                        <input type="hidden" name="id_pedido" value="<?php echo $value['id'] ?>">
                                        <input type="hidden" name="status" value="2">
                                        <div class="col float-end">
                                            <button type="button" class="btn text-white" data-bs-dismiss="modal">Cancelar <i class="bi bi-x"></i></button>
                                            <button id="button-mod" type="submit" class="btn text-white">Sim <i class="bi bi-check float-end"></i></button>
                                        </div>
                                    </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
    $('#button-mod').click(function () {
        $("#ped-separado<?php echo $value['id'] ?>").submit(function (e) {
            e.preventDefault()
            url = $(this).attr("action")
            $.ajax({
                data: $(this).serialize(),
                url: url,
                type: "POST",
                dataType: 'json',

                success: function (response) {
                    console.log(response)
                    title = ' <i class="bi bi-check2-square"></i> '
                    message = 'Pedido aguardando Retirada!'
                    template =
                        '<div class="alert alert-info bg-info" role="alert">' +
                        '<strong data-growl="title"></strong> <span data-growl="message"></span>' +
                        '</div>'

                        notification(title, message, template)
                    
                    // $("#container").load( " #container");
                    // $('.modal').load(' .modal');
                    $('.modal').modal('hide');
                    $("#pedidosSeparacao").load( " #pedidosSeparacao");
                    $("#pedidosRetirada").load( " #pedidosRetirada");

                    
                },

                error: function (response) {
                    title = ' <i class="bi bi-exclamation-circle"> </i> '
                    message = response.responseJSON.message
                    template =
                        '<div class="alert alert-danger bg-danger" role="alert">' +
                        '<strong data-growl="title"></strong> <span data-growl="message"></span>' +
                        '</div>'

                    notification(title, message, template)

                }
            })
        })
    })
    </script>
    </div>
    <form id="ped-separado<?php echo $value['id'] ?>" action="/mudar_status" method="post">
        <input type="hidden" name="id_pedido" value="<?php echo $value['id'] ?>">
        <input type="hidden" name="status" value="2">
    </form>
<?php } ?> 