<div class="container">
    <div class="row p-3 mt-2">
        
        <div class="col-6 p-3 text-center m-auto">
            <h4 for="">Inserir novo pedido</h4>
            <form id="novo-pedido" action="inserir_pedido" method="post">
                <div class="input-group mb-3">
                    <input type="text" class="form-control shadow" data-name="form-novo-pedido" name="numero_pedido" placeholder="Número do pedido" required>
                    <div class="input-group-append">
                        <button id="button-novo-pedido" type="submit" class="btn btn-success rounded shadow">Inserir <i class="bi bi-cart3"></i></button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-md-3 text-center mt-2">
            <button type="button" class="btn btn-success rounded shadow" data-bs-toggle="modal" data-bs-target="#pedidos_finalizados">Pedidos Finalizado <i class="bi bi-cart-check"></i></button>
        </div>
        <div class="col-md-3 text-center mt-2">
            <button type="button" class="btn btn-danger rounded shadow" data-bs-toggle="modal" data-bs-target="#pedidos_cancelados">Pedidos Cancelados <i class="bi bi-cart"></i></button>
        </div>
    </div>
</div>

<div id="container" class="container-fluid mt-2">
    <div class="row">
        <div class="col m-2 p-3">
            <div class="p-3 mt-2">
                <h3 class="text-center text-warning">Em Separação<i class="bi bi-cart-plus"></i></h3>
            </div>
            <div id="pedidosSeparacao" class="row justify-content-center p-2">
            <?php foreach ($this->view->listarPedidoSeparacao as $key => $value) { ?>
                <div class="card bg-white shadow rounded-custom border-0 m-2" style="width: 15rem;">
                    <div class="card-body">
                    <h5 class="text-warning float-start"><?php echo $value['numero_pedido'] ?></h5>
                    <button class=" btn btn-sm float-end" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-three-dots-vertical"></i></button>
                    <ul class="dropdown-menu shadow" aria-labelledby="navbarDropdown">
                        <li>
                            <a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#marcar-pedido-separado<?php echo $value['id'] ?>">Separado <i class="bi bi-cart-check float-end text-success"></i></a>
                        </li>
                        <li>
                            <button class="dropdown-item" id="button-delete-photo"
                                onclick="event.preventDefault();
                                document.getElementById('mudar_status<?php echo $value['id'] ?>').submit();">Cancelar <i class="text-danger bi bi-cart-x float-end"></i>
                            </button>
                            <form id="mudar_status<?php echo $value['id'] ?>" action="/mudar_status" method="POST" class="d-none">
                                <input name="id_pedido" type="hidden" value="<?php echo $value['id'] ?>">    
                                <input name="status" type="hidden" value="4">    
                            </form>
                        <li>
                            <a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#excluir-pedido<?php echo $value['id'] ?>">Excluir <i class="bi bi-trash float-end text-danger"></i></a>
                        </li>
                    </ul>
                    </div>
                </div>
                
                <!-- Modal excluir pedido -->
                <div class="modal fade" id="excluir-pedido<?php echo $value['id'] ?>" data-bs-backdrop="static" data-bs-backdrop="false" data-bs-keyboard="false" tabindex="-1" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered">
                        <div class="modal-content bg-transparent border-0">
                            <div class="container-fluid bg-dark text-white shadow">
                                <div class="modal-body p-1">
                                    <div class="row p-1">
                                        <div class="col-12 col-sm-12 p-3 m-auto">
                                            <div class="row p-3 m-auto">
                                                <div class=" col p-3 small mb-3">
                                                    <h5 class="text-center">Atenção <i class="bi bi-exclamation-triangle"></i></h5>
                                                    <div class="row g-3 mt-2">
                                                        <div class="col-12 text-center">
                                                            <h6>Deseja realmente excluir o pedodo?</h6>
                                                            <h6><?php echo $value['numero_pedido'] ?></h6>
                                                        </div>
                                                    </div>
                                                </div>
                                                <hr>
                                                <div class="col">
                                                    <div class="col float-end">
                                                        <button class="btn btn-sm text-white"
                                                        onclick="event.preventDefault();
                                                                document.getElementById('deletar_pedido<?php echo $value['id'] ?>').submit();">Sim <i class="bi bi-check"></i>
                                                        </button>
                                                        <form id="deletar_pedido<?php echo $value['id'] ?>" action="/excluir" method="POST" class="d-none">
                                                            <input name="numero_pedido" type="hidden" value="<?php echo $value['id'] ?>">       
                                                        </form>
                                                        <button type="button" class="btn btn-sm text-white" data-bs-dismiss="modal">Cancelar <i class="bi bi-x"></i></button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <?php } ?>
            </div>
        </div>

        <div class="col m-2 p-3">
            <div class="p-3 mt-2">
                <h3 class="text-center text-success">Aguardando Retirada <i class="bi bi-cart-check"></i></h3>
            </div>
            <div id="pedidosRetirada" class="row justify-content-center p-3">
            <?php foreach ($this->view->dados as $key => $value) { ?>
                <div class="card bg-white shadow rounded-custom border-0 m-2" style="width: 15rem;">
                    <div class="card-body">
                    <h5 class="text-success float-start"><?php echo $value['numero_pedido'] ?></h5>
                    <button class="btn btn-sm float-end" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-three-dots-vertical"></i></button>
                    <ul class="dropdown-menu shadow" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#retirar-pedido<?php echo $value['id'] ?>">Finalizar <i class="bi bi-cart-check float-end text-success"></i></a></li>
                        <li><button class="dropdown-item"
                                onclick="event.preventDefault();
                                document.getElementById('cancelar_pedido<?php echo $value['id'] ?>').submit();">Cancelar <i class="text-danger bi bi-cart-x float-end"></i>
                            </button>
                            <form id="cancelar_pedido<?php echo $value['id'] ?>" action="/mudar_status" method="POST" class="d-none">
                                <input name="id_pedido" type="hidden" value="<?php echo $value['id'] ?>">    
                                <input name="status" type="hidden" value="4">    
                            </form></li>
                        <li><a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#excluir-retirada<?php echo $value['id'] ?>">Excluir <i class="bi bi-trash float-end text-danger"></i></a></li>
                    </ul>
                    </div>
                </div>
                <!-- Modal excluir pedido-retirada -->
                <div class="modal fade" id="excluir-retirada<?php echo $value['id'] ?>" data-bs-backdrop="static" data-bs-backdrop="false" data-bs-keyboard="false" tabindex="-1" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered">
                        <div class="modal-content bg-transparent border-0">
                            <div class="container-fluid bg-dark text-white shadow">
                                <div class="modal-body p-1">
                                    <div class="row p-1">
                                        <div class="col-12 col-sm-12 p-3 m-auto">
                                            <div class="row p-3 m-auto">
                                                <div class=" col p-3 small mb-3">
                                                    <h5 class="text-center">Atenção <i class="bi bi-exclamation-triangle"></i></h5>
                                                    <div class="row g-3 mt-2">
                                                        <div class="col-12 text-center">
                                                            <h6>Deseja realmente excluir o pedodo?</h6>
                                                            <h6><?php echo $value['numero_pedido'] ?></h6>
                                                        </div>
                                                    </div>
                                                </div>
                                                <hr>
                                                <div class="col">
                                                    <div class="col float-end">
                                                    <button class="btn btn-sm text-white"
                                                    onclick="event.preventDefault();
                                                            document.getElementById('deletar_pedido<?php echo $value['id'] ?>').submit();">Sim <i class="bi bi-check"></i>
                                                    </button>
                                                    <form id="deletar_pedido<?php echo $value['id'] ?>" action="/excluir" method="POST" class="d-none">
                                                        <input name="numero_pedido" type="hidden" value="<?php echo $value['id'] ?>">       
                                                    </form>
                                                     <button type="button" class="btn btn-sm text-white" data-bs-dismiss="modal">Cancelar <i class="bi bi-x"></i></button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Modal Retirar Pedido -->
                <div class="modal fade" id="retirar-pedido<?php echo $value['id'] ?>" data-bs-backdrop="static" data-bs-backdrop="false" data-bs-keyboard="false" tabindex="-1" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered">
                        <div class="modal-content bg-transparent border-0">
                            <div class="container-fluid bg-white shadow">
                                <div class="modal-body p-1">
                                    <div class="row p-1">
                                        <div class="col-12 col-sm-12 p-3 m-auto">
                                            <div class="row p-3 m-auto">
                                                <div class=" col p-3 small mb-3">
                                                    <h5 class="text-center text-success">Retirada de Pedido <i class="bi bi-check"></i></h5>
                                                    <div class="row g-3 mt-2">
                                                        <div class="col-12 text-center">
                                                            <h6>Pedido: <?php echo $value['numero_pedido'] ?></h6>
                                                        </div>
                                                    </div>
                                                </div>
                                                <form action="retirar_pedido" method="post">
                                                    <div class="form-group">
                                                        <label>Nome do Responsável </label>
                                                        <input type="text" class="form-control" name="nome_responsavel">
                                                        <input type="hidden" class="form-control" name="id_pedido" value="<?php echo $value['id'] ?>" required>
                                                        <input type="hidden" class="form-control" name="status" value="3" required>
                                                        <input type="hidden" class="form-control" name="user" value="Pedro Silva" required>
                                                        </div>
                                                        <div class="form-group mt-1">
                                                        <label>Telefone</label>
                                                        <input type="text" class="form-control" name="telefone" placeholder="(21) 99999-9999" onkeypress="mask(this, mphone);" onblur="mask(this, mphone);" required>
                                                    </div>

                                                    <div class="form-group mt-1">
                                                        <label>Placa do Veículo</label>
                                                        <input type="text" class="form-control" name="placa_veiculo" placeholder="RIO1234" required>
                                                    </div>
                                                    <div class="form-group mt-1">
                                                        <label>Tipo Veículo</label>
                                                        <input type="text" class="form-control" name="tipo_veiculo" placeholder="Moto, Carro ou Outros" required>
                                                    </div>
                                                    <hr>
                                                    <div class="col">
                                                        <div class="col float-end">
                                                            <button type="button" class="btn" data-bs-dismiss="modal">Cancelar <i class="bi bi-x"></i></button>
                                                            <button type="submit" class="btn">Confirmar <i class="bi bi-check"></i></button>
                                                        </div>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            <?php } ?>
            </div>
        </div>
    </div>
</div>


<?php foreach ($this->view->listarPedidoSeparacao as $key => $value) { ?>
<div id="modal">
    <!-- Modal marcar-pedido-separado -->
    <div class="modal fade" id="marcar-pedido-separado<?php echo $value['id'] ?>" data-bs-backdrop="static" data-bs-backdrop="false" data-bs-keyboard="false" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content bg-transparent border-0">
                <div class="container-fluid bg-warning text-white shadow">
                    <div class="modal-body p-1">
                        <div class="row p-1">
                            <div class="col-12 col-sm-12 p-3 m-auto">
                                <div class="row p-3 m-auto">
                                    <div class=" col p-3 small mb-3">
                                        <h5 class="text-center">Atenção <i class="bi bi-exclamation-triangle"></i></h5>
                                        <div class="row g-3 mt-2">
                                            <div class="col-12 text-center">
                                                <h6>Deseja mover pedido para Aguardando Retirada?</h6>
                                                <h6>Pedido: <?php echo $value['numero_pedido'] ?></h6>
                                            </div>
                                        </div>
                                    </div>
                                    <hr>
                                    <div class="col">
                                    <form id="ped-separado<?php echo $value['id'] ?>" action="/mudar_status" method="post">
                                        <input type="hidden" name="id_pedido" value="<?php echo $value['id'] ?>">
                                        <input type="hidden" name="status" value="2">
                                        <div class="col float-end">
                                            <button type="button" class="btn text-white" data-bs-dismiss="modal">Cancelar <i class="bi bi-x"></i></button>
                                            <button id="button-mod" type="submit" class="btn text-white">Sim <i class="bi bi-check float-end"></i></button>
                                        </div>
                                    </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
    <form id="ped-separado<?php echo $value['id'] ?>" action="/mudar_status" method="post">
        <input type="hidden" name="id_pedido" value="<?php echo $value['id'] ?>">
        <input type="hidden" name="status" value="2">
    </form>
<?php } ?>


<!-- Modal Pedidos Finalizados -->
<div class="modal fade" id="pedidos_finalizados" data-bs-backdrop="static" data-bs-backdrop="false" data-bs-keyboard="false" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-xl modal-dialog-centered">
        <div class="modal-content bg-transparent border-0">
            <div class="container-fluid bg-white text-dark shadow">
                <div class="modal-body p-1">
                    <div class="row p-1">
                        <div class="col-12 col-sm-12 p-3 m-auto">
                            <div class="row p-3 m-auto">
                                <div class=" col p-3 small mb-3">
                                    <h5 class="text-center">Pedidos Finalizados <i class="bi bi-cart-check text-success"></i></h5>
                                    <div class="row g-3 mt-2">
                                        <div class="col-12 text-center">
                                        <table id="peds_finalizados" class="p-1 table table-responsive table-hover small" style="width:100%">
                                            <thead>
                                                <tr class="bg-success text-white">
                                                    <th>Numero Pedido</th>
                                                    <th>Liberado por</th>
                                                    <th>Retirado Por</th>
                                                    <th>Telefone</th>
                                                    <th>Tipo do Veiculo</th>
                                                    <th>Placa</th>
                                                    <th>Data da Retirada</th>
                                                    <!-- <th>Ação</th> -->
                                                </tr>
                                            </thead>
                                            <tbody class="font-color-darkgrey">
                                            <?php foreach ($this->view->peds_finalizados as $key => $value) { ?>
                                                <tr>
                                                    <td><?php echo $value['numero_pedido'] ?></td>
                                                    <td><?php echo $value['user_liberacao'] ?></td>
                                                    <td><?php echo $value['responsavel_veiculo'] ?></td>
                                                    <td><?php echo $value['telefone'] ?></td>
                                                    <td><?php echo $value['tipo_veiculo'] ?></td>
                                                    <td><?php echo $value['placa_veiculo'] ?></td>
                                                    <td><?php echo $value['data_retirada'] ?></td>
                                                </tr>
                                            <?php } ?>
                                            </tbody>
                                            <tfoot>
                                                <tr class="bg-success text-white">
                                                    <th>Numero Pedido</th>
                                                    <th>Liberado por</th>
                                                    <th>Retirado Por</th>
                                                    <th>Telefone</th>
                                                    <th>Tipo do Veiculo</th>
                                                    <th>Placa</th>
                                                    <th>Data da Retirada</th>
                                                </tr>
                                            </tfoot>
                                        </table>
                                        </div>
                                    </div>
                                </div>
                                <hr>
                                <div class="col">
                                    <div class="col float-end">
                                        <button type="button" class="btn btn-sm text-dark" data-bs-dismiss="modal">Voltar <i class="bi bi-x"></i></button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal Pedidos Cancelados -->
<div class="modal fade" id="pedidos_cancelados" data-bs-backdrop="static" data-bs-backdrop="false" data-bs-keyboard="false" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-xl modal-dialog-centered">
        <div class="modal-content bg-transparent border-0">
            <div class="container-fluid bg-white text-dark shadow">
                <div class="modal-body p-1">
                    <div class="row p-1">
                        <div class="col-12 col-sm-12 p-3 m-auto">
                            <div class="row p-3 m-auto">
                                <div class=" col p-3 small mb-3">
                                    <h5 class="text-center">Pedidos Cancelados <i class="bi bi-cart"></i></h5>
                                    <div class="row g-3 mt-2">
                                        <div class="col-12 text-center">
                                        <table id="peds_cancelados" class="p-1 table table-responsive table-hover small" style="width:100%">
                                        <thead>
                                                <tr class="bg-danger text-white">
                                                    <th>Numero Pedido</th>
                                                    <th>Status</th>
                                                    <th>Data da Inclusão</th>
                                                    <th>Data do Cancelamento</th>
                                                </tr>
                                            </thead>
                                            <tbody class="font-color-darkgrey">
                                            <?php foreach ($this->view->peds_cancelados as $key => $value) { ?>
                                                <tr>
                                                    <td><?php echo $value['numero_pedido'] ?></td>
                                                    <td><?php echo $value['descricao'] ?></td>
                                                    <td><?php echo $value['data_inclusao'] ?></td>
                                                    <td><?php echo $value['data_atualizacao'] ?></td>
                                                </tr>
                                            <?php } ?>
                                            </tbody>
                                            <tfoot>
                                                <tr class="bg-danger text-white">
                                                    <th>Numero Pedido</th>
                                                    <th>Status</th>
                                                    <th>Data da Inclusão</th>
                                                    <th>Data do Cancelamento</th>
                                                </tr>
                                            </tfoot>
                                        </table>
                                        </div>
                                    </div>
                                </div>
                                <hr>
                                <div class="col">
                                    <div class="col float-end">
                                        <button type="button" class="btn btn-sm text-dark" data-bs-dismiss="modal">Voltar <i class="bi bi-x"></i></button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>