<style>
    body {
        background-image: linear-gradient(to right, white, rgb(157, 99, 86)) !important;
        background-position: center !important;
        background-size: cover !important;
    }
</style>

<div class="container-fluid mt-1 mb-2">
    <div class="row p-3">
        <div class="row col-5">
            <div class="col-6 p-1">
                <div class="p-1">
                    <h2 class="text-center text-color-warning p-2 ped_fonte">Pedidos em Separação <i class="bi bi-cart-plus"></i></h2>
                </div>
                <div id="separacao" class="g-2 g-lg-3 ped_fonte mt-1 text-color-warning text-center"></div>
            </div>
            <div class="col-6 p-1">
                <div class="p-1">
                    <h2 class="text-center text-success rounded p-2 ped_fonte"> Aguardando Retirada <i class="bi bi-cart-check"></i></h2>
                </div>
                <div id="retirada" class="g-2 g-lg-3 ped_fonte mt-1 text-success text-center"></div>
            </div>
        </div>

        <div class="col-7 m-auto">
            <div class="col-12">
                <div class="text-center text-success">
                    <div id="logo" class="mt-1 p-1"></div>
                    <div id="video" class="mt-3 p-1"></div>
                    <div class="text-center text-dark mt-1">
                    <h3 id="dateTime"></h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<audio id="audio">
    <!-- <source src="Sounds/campanha-uso-de-mascaras.mp3" type="audio/mp3"> -->
</audio>