<div class="container-fluid mt-1 mb-2">
    <div class="row p-3">
        <div class="row col-6">
            <div class="col-6 p-1">
                <div class="bg-light rounded-pill">
                    <h2 class="text-center text-color-warning p-2 ped_fonte">Pedido em Separação <i class="fa fa-cart-arrow-down"></i></h2>
                </div>
                <div id="retirando1" class="g-2 g-lg-3 ped_fonte mt-1 text-color-warning text-center"></div>
            </div>
            <div class="col-6 p-1">
                <div class="bg-light rounded-pill">
                    <h2 class="text-center text-success rounded p-2 ped_fonte"> Aguardando Retirada <i class="fa fa-check-circle"></i></h2>
                </div>
                <div id="retirando2" class="g-2 g-lg-3 ped_fonte mt-1 text-success text-center"></div>
            </div>
        </div>

        <div class="col-6 m-auto">
            <div class="col-12">
                <div class="text-center text-success">
                    <img src="img/logo.png" alt="Pro" class="" width="180px" height="130px">
                    <div id="video" class="mt-3 p-1">
                    </div>
                    <div class="text-center text-dark mt-1">
                    <h3 id="dateTime"></h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- <audio id="audio">
    <source src="Sounds/campanha-uso-de-mascaras.mp3" type="audio/mp3">
</audio> -->