<html>

<head>
	<meta charset="utf-8" />
	<title>Painel</title>

	<link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,700,900" rel="stylesheet">

	<link rel="stylesheet" type="text/css" href="/css/style.css">

	<!-- Bootstrap -->
	<link rel="stylesheet" href=" /bootstrap/css/bootstrap.min.css">

	<!-- Bootstrap icons-->
	<link rel="stylesheet" href="/bootstrap/bootstrap-icons-1.9.1/bootstrap-icons.css">

	<!-- animate CSS -->
	<link rel="stylesheet" href="/css/animate.css">

	<!-- Datatables CSS -->
	<link rel="stylesheet" href="/css/data-tables/data-tables.css">
	<!-- <link rel="stylesheet" href="/css/data-tables/tables.css"> -->

	<!-- notification CSS -->
	<link rel="stylesheet" href="/css/notification/notification.css">


</head>

<body>
	<?= $this->content() ?>
	

	<!-- JavaScript Bundle / Popper -->
	<script src="/js/popper/popper.mim.js"></script>
	<script src="/bootstrap/js/bootstrap.bundle.min.js"></script>

	<!-- jquery -->
	<script src="/js/jquery/jquery-3.6.0.min.js"></script>

	<script src="/js/custom-js/scripts.js"></script>
	<script src="/js/data-tables/jquery-data-tables.min.js"></script>
	<script src="/js/data-tables/datatable.js"></script>

	<!--  notification JS -->
	<script src="/js/notification/bootstrap-growl.min.js"></script>
	


</body>

</html>