<html>

<head>
	<meta charset="utf-8" />
	<title>Painel</title>

	<link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,700,900" rel="stylesheet">

	<link rel="stylesheet" type="text/css" href="/css/style.css">

	<!-- Bootstrap -->
	<link rel="stylesheet" href=" /dist/css/bootstrap.min.css">

	<!-- Bootstrap icons-->
	<link rel="stylesheet" href="/bootstrap-icons-1.9.1/bootstrap-icons.css">

</head>

<body>
	<?= $this->content() ?>
	

	<!-- JavaScript Bundle / Popper -->
	<script src="dist/js/popper/popper.min.js"></script>
	<script src="dist/js/bootstrap.bundle.min.js"></script>

	<!-- jquery -->
	<script src="/js/jquery-3.6.0.min.js"></script>

	<script src="/js/custom-js/scripts.js"></script>
	


</body>

</html>